In [23]:
from sqlalchemy import create_engine
from getpass import getpass

password = getpass("Enter MySQL root password: ")

engine = create_engine(
    f"mysql+pymysql://root:{password}@localhost/airbnb_project"
)

print("Engine created")

Enter MySQL root password:  ········

Engine created

In [24]:
from sqlalchemy import text

with engine.connect() as connection:
    result = connection.execute(text("SELECT DATABASE();"))
    print("Connected to:", result.scalar())

Connected to: airbnb_project

In [25]:
airbnb.to_sql(
    name="airbnb_listings",
    con=engine,
    if_exists="replace",
    index=False
)

print("Dataset uploaded to MySQL")

Dataset uploaded to MySQL

In [26]:
print("Python rows:", len(airbnb))

query = """
SELECT COUNT(*) AS total_rows
FROM airbnb_listings;
"""

pd.read_sql(query, engine)

Python rows: 604

   total_rows
0         604

In [27]:
query = """
SELECT *
FROM airbnb_listings
LIMIT 10;
"""

sql_df = pd.read_sql(query, engine)

sql_df

,property_name,amenities,property_type,city,country,month,price_in_dollar,rating,number_of_reviews,rating_rank,...,hot_tub,fireplace,wood_stove,parking,kitchen,beach,waterfront,sea_view,mountain_view,amenity_count
0,"Farm stay in Saint Marys, Canada",Cozy Farm Stay Getaway,Farm stay,Saint Marys,Canada,June,99.0,4.86,183.0,385,...,0,0,0,0,0,0,0,0,0,0
1,"Guesthouse in Naalehu, Hawaii, US",The Ohana,Guesthouse,Naalehu,"Hawaii, US",June,99.0,4.86,182.0,387,...,0,0,0,0,0,0,0,0,0,0
2,"Villa in Koh Yao Noi, Thailand","Eagles Nest, Luxury Villa, Koh Yao Noi",Villa,Koh Yao Noi,Thailand,June,986.0,4.95,43.0,175,...,0,0,0,0,0,0,0,0,0,0
3,"Loft in Jelutong, Malaysia",#Maritime*3*The Rhythm of the Sea @ 日出无敌全海景,Loft,Jelutong,Malaysia,June,98.0,4.56,93.0,649,...,0,0,0,0,0,0,0,0,0,0
4,"Treehouse in Fountana, Greece",Nasos' Treehouse,Treehouse,Fountana,Greece,June,98.0,4.91,32.0,279,...,0,0,0,0,0,0,0,0,0,0
5,"Cabin in Rosenthal-Bielatal, Germany",Mountain hut in the Elbe sandstone with log ca...,Cabin,Rosenthal-Bielatal,Germany,June,98.0,4.78,169.0,544,...,0,0,0,0,0,0,0,0,0,1
6,"Treehouse in Verson, France",2 Cabins perched above a pond!,Treehouse,Verson,France,June,98.0,4.94,530.0,185,...,0,0,0,0,0,0,0,0,0,0
7,"Treehouse in Fountana, Greece",Nasos' Treehouse,Treehouse,Fountana,Greece,June,98.0,4.81,98.0,501,...,0,0,0,0,0,0,0,0,0,0
8,"Treehouse in Verson, France",2 Cabins perched above a pond!,Treehouse,Verson,France,June,98.0,4.91,68.0,273,...,0,0,0,0,0,0,0,0,0,0
9,"Apartment in Carolina, Puerto Rico",Isla Verde Beach Studio {105},Apartment,Carolina,Puerto Rico,July,97.0,4.67,433.0,614,...,0,0,0,0,0,1,0,0,0,1

In [29]:
query = """
SELECT
    Country,
    COUNT(*) AS total_properties,
    ROUND(AVG(`Price(in dollar)`), 2) AS average_price,
    ROUND(AVG(Rating), 2) AS average_rating
FROM airbnb_listings
GROUP BY Country
ORDER BY total_properties DESC;
"""

country_summary = pd.read_sql(query, engine)

country_summary

,Country,total_properties,average_price,average_rating
0,Indonesia,92,203.25,4.86
1,Thailand,51,110.12,4.84
2,Canada,43,222.12,4.89
3,Mexico,36,93.86,4.78
4,UK,30,153.37,4.93
...,...,...,...,...
61,"Kabupaten Gianyar, Indonesia",1,137.00,4.91
62,Curaçao,1,125.00,4.78
63,"Virginia, US",1,125.00,4.82
64,Switzerland,1,109.00,4.80
65,Jamaica,1,102.00,4.88